2
AntonFedorovich95/hogwarts-school pull request #8
Opened 2022-06-29 08:57 UTC by AntonFedorovich95

2022-06-29 18:16 UTC, OlgaLugacheva requested changes

2022-06-29 18:16 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/StudentControllerCrmTests.java
> +        assertEquals(HttpStatus.CREATED, response.getStatusCode());
у тебя контроллер возвращает статус OK 200 с ним и надо сравнивать HttpStatus.OK

2022-06-29 18:16 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/StudentControllerCrmTests.java
> +        HttpEntity<Student> entity = new HttpEntity<>(student);
из-за специфического метода  existById необходимо добавить
when(studentRepository.existsById(any())).thenReturn(true);

2022-06-29 18:16 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/FacultyControllerMvcTests.java
> +
добавить when(facultyRepository.existsById(eq(id))).thenReturn(true);

2022-06-29 18:16 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/FacultyControllerMvcTests.java
> +                .get("/faculty" + id)
`"/faculty/" + id`

2022-06-29 18:16 UTC, OlgaLugacheva commented on src/test/java/ru/hogwarts/school/FacultyControllerMvcTests.java
> +                .andExpect(jsonPath("$.id").value(id))
здесь от энедпоинта мы ожидаем список , значит и сравнивать нужно с элементами списка
`"$[0].id" `и т.д.

2022-06-30 08:37 UTC, AntonFedorovich95 commented
Исправил

2022-07-11 05:22 UTC, AntonFedorovich95 commented
Исправил

2022-07-15 10:11 UTC, merged